# Generated by Django 2.2.20 on 2021-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20210422_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=120, verbose_name='Receiver Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_city',
            field=models.CharField(max_length=50, verbose_name='Receiver City'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(max_length=50, verbose_name='Receiver Name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_state',
            field=models.CharField(max_length=50, verbose_name='Receiver State'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=120, verbose_name='Sender Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_city',
            field=models.CharField(max_length=50, verbose_name='Sender City'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(max_length=50, verbose_name='Sender Name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_state',
            field=models.CharField(max_length=50, verbose_name='Sender State'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=50, verbose_name='Tracking Number'),
        ),
    ]
