# Generated by Django 2.2.20 on 2021-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20210422_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='arrival_status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking Number'),
        ),
    ]
