# Generated by Django 2.2.20 on 2021-04-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20210422_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Shipment Status', 'verbose_name_plural': 'Shipment Statuses'},
        ),
    ]
