# Generated by Django 2.2.20 on 2021-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20210423_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
